PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aw: <http://rdf.freebase.com/ns/visual_art.artwork.>
PREFIX fb: <http://rdf.freebase.com/ns/>
PREFIX local: <dataflow#>

SELECT DISTINCT ?area ?relatedArtwork
WHERE {
  {} UNION {
    GRAPH <place.filters> {
      GRAPH <var.common> {
        SELECT ?selectedArtwork ?relatedArtwork
        WHERE {
          ?relatedArtwork
            a fb:visual_art.artwork;
            fb:type.object.name ?name;
            [...]
          FILTER(?relatedArtwork != ?selectedArtwork).
          FILTER(STRSTARTS(STR(?relatedArtwork),
                           STR(fb:m))). } }
      GRAPH <var.selected> {
        GRAPH local:selected {
          local:global
            local:selectedArtwork ?selectedArtwork. } }
    }
  }
}
ORDER BY ?area

