PREFIX nn:    <http://www.swows.org/xml/no-namespace#>
PREFIX xml:   <http://www.swows.org/2013/07/xml-dom#>
PREFIX svg:   <http://www.w3.org/2000/svg#>
PREFIX xlink: <http://www.w3.org/1999/xlink#>
PREFIX swi:   <http://www.swows.org/instance#>

PREFIX fb: <http://rdf.freebase.com/ns/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbp-ont: <http://dbpedia.org/ontology/>
PREFIX umbel-sc: <http://umbel.org/umbel/sc/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ff: <http://factforge.net/>
PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>

PREFIX sparql-res: <http://www.w3.org/2005/sparql-results#>

CONSTRUCT {

  <>
    <#padding> ?padding;
    <#smallImagesWidth> ?smallImagesWidth;
    <#smallImagesHeight> ?smallImagesHeight;
    <#windowWidth> ?windowWidth;
    <#windowHeight> ?windowHeight.

  <#svgDoc>
    a xml:Document ;
    xml:hasChild <#svgElem> .

  <#svgElem>
    a svg:svg ;
    nn:version "1.1" ;
    nn:width ?windowWidth ;
    nn:height ?windowHeight ;
    xml:hasChild <#defs>, <#centralImage>, <#infoBox>, <#topBar>, <#bottomBar>, <#leftBar>, <#rightBar>.

  <#defs> a svg:defs.

  <#centralImage>
    a svg:image ;
    nn:x ?centralImageX ;
    nn:y ?centralImageY ;
    nn:width ?centralImageWidth ;
    nn:height ?centralImageHeight .

  <#infoBox> 
    a svg:g;
    xml:hasChild <#infoBoxName>, <#infoBoxArtist>, <#infoBoxArtForm>, <#infoBoxArtGenre>, <#infoBoxArtSubject>, <#infoBoxDate>.

  <#infoBoxName>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxNameY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#infoBoxArtist>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxArtistY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#infoBoxArtForm>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxArtFormY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#infoBoxArtGenre>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxArtGenreY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#infoBoxArtSubject>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxArtSubjectY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#infoBoxDate>
    a svg:text ;
    nn:x ?infoBoxX ;
    nn:y ?infoBoxDateY ;
    nn:width ?infoBoxWidth ;
    nn:height ?infoBoxFieldHeight .

  <#topBar> a svg:g.

  <#topBarArea>
    a <#ImageArea>;
    <#svgElement> <#topBar>;
    <#x> ?topBarX;
    <#y> ?topBarY;
    <#width> ?topBarWidth;
    <#height> ?topBarHeight;
    <#cols> ?numTopImages;
    <#rows> 1.

  <#bottomBar> a svg:g.

  <#bottomBarArea>
    a <#ImageArea>;
    <#svgElement> <#bottomBar>;
    <#x> ?bottomBarX;
    <#y> ?bottomBarY;
    <#width> ?bottomBarWidth;
    <#height> ?bottomBarHeight;
    <#cols> ?numBottomImages;
    <#rows> 1.

  <#leftBar> a svg:g.

  <#leftBarArea>
    a <#ImageArea>;
    <#svgElement> <#leftBar>;
    <#x> ?leftBarX;
    <#y> ?leftBarY;
    <#width> ?leftBarWidth;
    <#height> ?leftBarHeight;
    <#cols> 1;
    <#rows> ?numLeftImages.

  <#rightBar> a svg:g.

  <#rightBarArea>
    a <#ImageArea>;
    <#svgElement> <#rightBar>;
    <#x> ?rightBarX;
    <#y> ?rightBarY;
    <#width> ?rightBarWidth;
    <#height> ?rightBarHeight;
    <#cols> 1;
    <#rows> ?numRightImages.

}
WHERE {
  BIND(1200 as ?windowWidth).
  BIND(800 as ?windowHeight).
  BIND(10 as ?padding).
  BIND(100 as ?smallImagesWidth).
  BIND(100 as ?smallImagesHeight).

  BIND(?smallImagesHeight as ?topBarHeight).
  BIND(?smallImagesHeight as ?bottomBarHeight).
  BIND(?smallImagesWidth as ?leftBarWidth).
  BIND(?smallImagesWidth as ?rightBarWidth).

  BIND(?leftBarWidth+2*?padding AS ?centralPanelX).
  BIND(?topBarHeight+2*?padding AS ?centralPanelY).
  BIND(?windowWidth-?leftBarWidth-?rightBarWidth-4*?padding AS ?centralPanelWidth).
  BIND(?windowHeight-?topBarHeight-?bottomBarHeight-4*?padding AS ?centralPanelHeight).

  BIND(?centralPanelWidth AS ?topBarWidth).
  BIND(?centralPanelWidth AS ?bottomBarWidth).

  BIND(?centralPanelX AS ?topBarX).
  BIND(?padding AS ?topBarY).
  BIND(?centralPanelX AS ?bottomBarX).
  BIND(?centralPanelY+?centralPanelHeight+?padding AS ?bottomBarY).

  BIND(?windowHeight-2*?padding AS ?leftBarHeight).
  BIND(?windowHeight-2*?padding AS ?rightBarHeight).

  BIND(?padding AS ?leftBarX).
  BIND(?padding AS ?leftBarY).
  BIND(?centralPanelX+?centralPanelWidth+?padding AS ?rightBarX).
  BIND(?padding AS ?rightBarY).

  BIND(250 as ?infoBoxWidth).
#  BIND(80 as ?infoBoxHeight).
  BIND(25 as ?infoBoxFieldHeight).

  BIND(?centralPanelX+?infoBoxWidth AS ?centralImageX).
  BIND(?centralPanelY AS ?centralImageY).
  BIND(?centralPanelWidth-?infoBoxWidth AS ?centralImageWidth).
  BIND(?centralPanelHeight AS ?centralImageHeight).

  BIND(FLOOR((?topBarWidth-?smallImagesWidth)/(?smallImagesWidth+?padding)+1) AS ?numTopImages).
  BIND(FLOOR((?bottomBarWidth-?smallImagesWidth)/(?smallImagesWidth+?padding)+1) AS ?numBottomImages).
  BIND(FLOOR((?leftBarHeight-?smallImagesHeight)/(?smallImagesHeight+?padding)+1) AS ?numLeftImages).
  BIND(FLOOR((?rightBarHeight-?smallImagesHeight)/(?smallImagesHeight+?padding)+1) AS ?numRightImages).

  BIND(?centralPanelX AS ?infoBoxX).
  BIND(?centralImageY AS ?infoBoxY).
#  BIND(?centralPanelWidth AS ?infoBoxWidth).
  BIND(?centralPanelHeight AS ?infoBoxHeight).

  BIND(?infoBoxY+?infoBoxFieldHeight AS ?infoBoxNameY).
  BIND(?infoBoxY+2*?infoBoxFieldHeight AS ?infoBoxArtistY).
  BIND(?infoBoxY+3*?infoBoxFieldHeight AS ?infoBoxArtFormY).
  BIND(?infoBoxY+4*?infoBoxFieldHeight AS ?infoBoxArtGenreY).
  BIND(?infoBoxY+5*?infoBoxFieldHeight AS ?infoBoxArtSubjectY).
  BIND(?infoBoxY+6*?infoBoxFieldHeight AS ?infoBoxDateY).

}

