prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dbpprop: <http://dbpedia.org/property/>
prefix dbpedia: <http://dbpedia.org/resource/>
prefix fb: <http://rdf.freebase.com/ns/> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 

select distinct ?author ?authorLabel
where {
  service <http://factforge.net/sparql> {
    ?author
      a fb:book.author ;
      a fb:film.film_story_contributor ;
      skos:prefLabel ?authorLabel .
    ?book
      a fb:book.book ;
      fb:book.written_work.author ?author ;
      fb:media_common.adapted_work.adaptations [ a fb:film.film ] .
  }
  FILTER( substr( str(?author),0, strlen(str(fb:))+2 ) = str(fb:m)).
} 